import "./globals.css"
import LayoutWrapper from "./layoutWrapper"
import { Montserrat, Climate_Crisis } from "next/font/google"

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-montserrat",
})

const climate = Climate_Crisis({
  subsets: ["latin"],
  variable: "--font-climate",
})

export const metadata = {
  icons: {
    icon: "/logo_Nabeel.svg",
  },
  title: "My Portfolio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body className={`${montserrat.className} ${climate.variable} bg-[#232023] text-white`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  )
}